read_data <- function(file) {
  # Reads data generated by the 01_tidy_data.R script with the correct column
  # specification for the factors.
  #
  # Args:
  #   file: Path to the file.
  #
  # Returns:
  #   A tibble with the factor columns parsed correctly.
  
  require(readr)
  
  read_csv(
    file,
    col_types = cols(
      time = col_factor(1:4),
      group = col_factor(c("Control", "Exercise")),
      surgery = col_factor(c("RYGB", "Sleeve")),
      sex = col_factor(c("Male", "Female")),
      menopause = col_factor(c("No", "Yes", "Male")),
      pre_diabetes = col_factor(c("No", "Yes")),
      diabetes = col_factor(c("No", "Yes")),
      thiazides = col_factor(c("No", "Yes")),
      smoker = col_factor(c("No", "Yes")),
      attend_cat = col_factor(
        c(
          "Control",
          "Under 50% training attendance",
          "Over 50% training attendance"
        )
      )
    )
  )
}
